In [1]:
import numpy as np

Kreiranje nizova

In [2]:
# Pravimo niz duzine 3
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [3]:
# Prikazujemo tip objekta na standardni izlaz
print(type(a))        

<class 'numpy.ndarray'>


In [4]:
# "(3,)" (nedostatak drugog indeksa oznacava da je u pitanju niz)
print('a.shape', a.shape)
print(f'a.shape {a.shape}')

a.shape (3,)
a.shape (3,)


In [5]:
# "1 2 3" <- indeksiranje
print(a[0], a[1], a[2])

1 2 3


In [6]:
# Menjanje elementa nizu
a[0] = 5
print(a)

[5 2 3]


In [7]:
# Pravimo visedimenzioni niz dimenzija (2, 3)
b = np.array([[1,2,3],[4,5,6]])

# "(2, 3)" <- 2 vrste, 3 kolone
print(b.shape)                      
print(b[0, 0], b[0, 1], b[1, 0])
print(b[0][0], b[0][1], b[1][0])

# Preporuka je koristiti [i, j] umesto [i][j].

(2, 3)
1 2 4
1 2 4


Inicijalizacija nizova

In [9]:
a = np.zeros((2,2))                 # Pravi se matrica dimenzija (2, 2) ciji su elementi 0
print(a)                            # "[[ 0.  0.]
                                    #   [ 0.  0.]]"

b = np.ones((1,2))                  # Pravi se matrica dimenzija (1, 2) ciji su elementi 1
print(b)                            # "[[ 1.  1.]]"

c = np.full((2,2), 7)               # Pravi se matrica dimenzija (2, 2) ciji su elementi 7
print(c)                            # "[[ 7.  7.]
                                    #   [ 7.  7.]]"

d = np.eye(2)                       # Pravi se jedinicna matrica dimenzija (2, 2)
print(d)                            # "[[ 1.  0.]
                                    #   [ 0.  1.]]"

np.random.seed(42)                  # Postavljamo seed ukoliko zelimo da mozemo reprodukovati pseudoslucajne brojeve
e = np.random.random((2,2))         # Pravi se matrica dimenzija (2, 2) cije su vrednosti iz uniformne raspodele [0, 1]
print(e)                            # "[[0.37454012 0.95071431]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


Indeksiranje nizova

In [10]:
# Pravimo matricu dimenzija (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4],  [5, 6, 7, 8],  [9, 10, 11, 12]])
print("a = \n{}".format(a))

# Koristimo odsecanje (eng. slicing) da uzmemo podniz koji se
# sastoji od prve dve vrste, pri cemu uzimamo kolone 1 i 2.
# Time dobijamo podniz dimenzija (2, 2).
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print("\na[:2, 1:3] = b = \n{}".format(b))

# Odsecanje ne pravi novi niz vec daje 'pogled' na originalni, tako
# da ukoliko menjamo dobijeni podniz, menjamo i originalni.
print(a[0, 1])   # "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # "77"

a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a[:2, 1:3] = b = 
[[2 3]
 [6 7]]
2
77


In [11]:
slice_copy = a[:2, 1:3].copy()
slice_copy[0,0] = 1000
print(slice_copy)
print(a)

[[1000    3]
 [   6    7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Racun nad nizovima

In [12]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print('x\n{}'.format(x))
print('y\n{}\n'.format(x))

x
[[1. 2.]
 [3. 4.]]
y
[[1. 2.]
 [3. 4.]]



In [13]:
# Pokoordinatno sabiranje
# [[ 6.0  8.0]
#  [10.0 12.0]]
print('x + y\n{}'.format(x + y))
print('np.add(x, y)\n{}\n'.format(np.add(x, y)))

x + y
[[ 6.  8.]
 [10. 12.]]
np.add(x, y)
[[ 6.  8.]
 [10. 12.]]



In [14]:
# Pokoordinatno oduzimanje
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print('x - y\n{}'.format(x - y))
print('np.subtract(x, y)\n{}\n'.format(np.subtract(x, y)))

x - y
[[-4. -4.]
 [-4. -4.]]
np.subtract(x, y)
[[-4. -4.]
 [-4. -4.]]



In [15]:
# Pokoordinatno mnozenje
# [[ 5.0 12.0]
#  [21.0 32.0]]
print('x * y\n{}'.format(x * y))
print('np.multiply(x, y)\n{}\n'.format(np.multiply(x, y)))

x * y
[[ 5. 12.]
 [21. 32.]]
np.multiply(x, y)
[[ 5. 12.]
 [21. 32.]]



In [16]:
# Pokoordinatno deljenje
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print('x / y\n{}'.format(x / y))
print('np.divide(x, y)\n{}\n'.format(np.divide(x, y)))

x / y
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
np.divide(x, y)
[[0.2        0.33333333]
 [0.42857143 0.5       ]]



In [17]:
# Pokoordinatno izracunavanje funkcije 'sqrt'
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print('np.sqrt(x)\n{}\n'.format(np.sqrt(x)))

np.sqrt(x)
[[1.         1.41421356]
 [1.73205081 2.        ]]



In [18]:
# Matricno mnozenje se izvodi funkcijom 'dot',
# i treba biti pazljiv, * izvodi pokoordinatno mnozenje a ne matricno.
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
# Matricno mnozenje; proizvodi matricu (2, 2)
# [[19 22]
#  [43 50]]
print('x.dot(y)\n{}'.format(x.dot(y)))
print('np.dot(x, y)\n{}\n'.format(np.dot(x, y)))

x.dot(y)
[[19 22]
 [43 50]]
np.dot(x, y)
[[19 22]
 [43 50]]



In [19]:
# 'dot' se moze koristiti i za skalarni proizvod
v = np.array([9,10])
w = np.array([11, 12])
# "219"
print('v.dot(w)\n{}'.format(v.dot(w)))
print('np.dot(v, w)\n{}'.format(np.dot(v, w)))

v.dot(w)
219
np.dot(v, w)
219


In [20]:
# Ax = b
A = np.array([
    [2,0],
    [0,2]
])
b = np.array([3.4, 7.8])

In [21]:
A_inv = np.linalg.inv(A)
A_inv

array([[0.5, 0. ],
       [0. , 0.5]])

In [22]:
x = A_inv.dot(b)
x

array([1.7, 3.9])

In [23]:
A.dot(x)

array([3.4, 7.8])